name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: latest

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Build documentation
        run: |
          uv run mkdocs build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
